"""add last_edited_by to upload_requests

Revision ID: 0660d20afdac
Revises: bd1c814beae3
Create Date: 2026-01-06 18:09:47.096347

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlmodel.sql.sqltypes import AutoString

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0660d20afdac"
down_revision: Union[str, Sequence[str], None] = "bd1c814beae3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "upload_requests",
        sa.Column("last_edited_by", AutoString(length=255), nullable=True),
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_upload_requests_last_edited_by"),
        "upload_requests",
        ["last_edited_by"],
        unique=False,
        if_not_exists=True,
    )
    op.create_foreign_key(
        op.f("fk_upload_requests_last_edited_by_users"),
        "upload_requests",
        "users",
        ["last_edited_by"],
        ["userid"],
        if_not_exists=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_upload_requests_last_edited_by_users"),
        "upload_requests",
        type_="foreignkey",
        if_exists=True,
    )
    op.drop_index(
        op.f("ix_upload_requests_last_edited_by"),
        table_name="upload_requests",
        if_exists=True,
    )
    op.drop_column("upload_requests", "last_edited_by", if_exists=True)
    # ### end Alembic commands ###
