"""add_celery_task_id_to_upload_requests

Revision ID: 17859f360896
Revises: 0660d20afdac
Create Date: 2026-01-11 12:52:22.146034

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "17859f360896"
down_revision: Union[str, Sequence[str], None] = "0660d20afdac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "upload_requests",
        sa.Column(
            "celery_task_id",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("upload_requests", "celery_task_id")
    # ### end Alembic commands ###
