"""Add indexes for performance optimization

Revision ID: 25ebee3eeed4
Revises: 7a39cf636b76
Create Date: 2025-12-31 15:47:40.710925

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "25ebee3eeed4"
down_revision: Union[str, Sequence[str], None] = "7a39cf636b76"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_batches_created_at"),
        "batches",
        ["created_at"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_batches_updated_at"),
        "batches",
        ["updated_at"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_upload_requests_created_at"),
        "upload_requests",
        ["created_at"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_upload_requests_updated_at"),
        "upload_requests",
        ["updated_at"],
        unique=False,
        if_not_exists=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_upload_requests_updated_at"), table_name="upload_requests")
    op.drop_index(op.f("ix_upload_requests_created_at"), table_name="upload_requests")
    op.drop_index(op.f("ix_batches_updated_at"), table_name="batches")
    op.drop_index(op.f("ix_batches_created_at"), table_name="batches")
    # ### end Alembic commands ###
