"""add copyright_override to upload_requests

Revision ID: 53640eac191d
Revises: 3f0f4e5a2b1c
Create Date: 2026-01-04 10:28:59.842532

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "53640eac191d"
down_revision: Union[str, Sequence[str], None] = "3f0f4e5a2b1c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "upload_requests", sa.Column("copyright_override", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("upload_requests", "copyright_override")
    # ### end Alembic commands ###
