"""drop celery tables

Revision ID: 5be0bf0d65f8
Revises: 05cabbf622bd
Create Date: 2025-12-23 09:02:06.799508

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5be0bf0d65f8"
down_revision: Union[str, Sequence[str], None] = "05cabbf622bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("name"), table_name="kombu_queue", if_exists=True)
    op.drop_index(op.f("taskset_id"), table_name="celery_tasksetmeta", if_exists=True)
    op.drop_index(op.f("task_id"), table_name="celery_taskmeta", if_exists=True)
    op.drop_index(
        op.f("ix_kombu_message_timestamp"), table_name="kombu_message", if_exists=True
    )
    op.drop_index(
        op.f("ix_kombu_message_timestamp_id"),
        table_name="kombu_message",
        if_exists=True,
    )
    op.drop_index(
        op.f("ix_kombu_message_visible"), table_name="kombu_message", if_exists=True
    )
    op.drop_table("message_id_sequence", if_exists=True)
    op.drop_table("queue_id_sequence", if_exists=True)
    op.drop_table("task_id_sequence", if_exists=True)
    op.drop_table("taskset_id_sequence", if_exists=True)
    op.drop_table("celery_taskmeta", if_exists=True)
    op.drop_table("celery_tasksetmeta", if_exists=True)
    op.drop_table("kombu_message", if_exists=True)
    op.drop_table("kombu_queue", if_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    pass
