"""drop last_edited_by from upload_requests

Revision ID: 5cc957424c9d
Revises: 8b31e3fb791b
Create Date: 2026-04-05 20:24:15.634982

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5cc957424c9d"
down_revision: Union[str, Sequence[str], None] = "8b31e3fb791b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_upload_requests_last_edited_by"), table_name="upload_requests"
    )
    op.drop_constraint(
        op.f("fk_upload_requests_last_edited_by_users"),
        "upload_requests",
        type_="foreignkey",
    )
    op.drop_column("upload_requests", "last_edited_by")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    raise NotImplementedError("downgrade not supported")
