"""update wikitext and sdc to non-nullable

Revision ID: 7a39cf636b76
Revises: 5be0bf0d65f8
Create Date: 2025-12-28 12:08:30.827803

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a39cf636b76"
down_revision: Union[str, Sequence[str], None] = "5be0bf0d65f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("UPDATE upload_requests SET wikitext = '' WHERE wikitext IS NULL")
    op.execute("UPDATE upload_requests SET sdc = JSON_ARRAY() WHERE sdc IS NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
