"""add presets table

Revision ID: 8b31e3fb791b
Revises: 324d2fe7d7ec
Create Date: 2026-02-22 14:03:04.650383

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8b31e3fb791b"
down_revision: Union[str, Sequence[str], None] = "324d2fe7d7ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "presets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "userid", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "handler", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column(
            "title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "title_template",
            sqlmodel.sql.sqltypes.AutoString(length=500),
            nullable=False,
        ),
        sa.Column("labels", sa.JSON(), nullable=True),
        sa.Column(
            "categories", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.Column("exclude_from_date_category", sa.Boolean(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["userid"],
            ["users.userid"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_presets_handler"), "presets", ["handler"], unique=False)
    op.create_index(
        op.f("ix_presets_is_default"), "presets", ["is_default"], unique=False
    )
    op.create_index(op.f("ix_presets_userid"), "presets", ["userid"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_presets_userid"), table_name="presets")
    op.drop_index(op.f("ix_presets_is_default"), table_name="presets")
    op.drop_index(op.f("ix_presets_handler"), table_name="presets")
    op.drop_table("presets")
    # ### end Alembic commands ###
