"""add edit_group_id to batches

Revision ID: b6b446c58114
Revises: 17859f360896
Create Date: 2026-02-17 18:11:22.408929

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlmodel.sql.sqltypes import AutoString

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b6b446c58114"
down_revision: Union[str, Sequence[str], None] = "17859f360896"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_kombu_message_timestamp"), table_name="kombu_message")
    op.drop_index(op.f("ix_kombu_message_timestamp_id"), table_name="kombu_message")
    op.drop_index(op.f("ix_kombu_message_visible"), table_name="kombu_message")
    op.drop_table("kombu_message", if_exists=True)
    op.drop_index(op.f("taskset_id"), table_name="celery_tasksetmeta")
    op.drop_table("celery_tasksetmeta", if_exists=True)
    op.drop_index(op.f("name"), table_name="kombu_queue")
    op.drop_table("kombu_queue", if_exists=True)
    op.drop_index(op.f("task_id"), table_name="celery_taskmeta")
    op.drop_table("celery_taskmeta", if_exists=True)
    op.drop_table("message_id_sequence", if_exists=True)
    op.drop_table("queue_id_sequence", if_exists=True)
    op.drop_table("task_id_sequence", if_exists=True)
    op.drop_table("taskset_id_sequence", if_exists=True)
    op.add_column(
        "batches", sa.Column("edit_group_id", AutoString(length=12), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("batches", "edit_group_id")
    # ### end Alembic commands ###
