"""add collection and token to upload_requests

Revision ID: ed3e8b47a240
Revises: 96cbd345d014
Create Date: 2025-12-12 13:12:12.851880

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ed3e8b47a240"
down_revision: Union[str, Sequence[str], None] = "96cbd345d014"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "upload_requests",
        sa.Column("collection", sa.String(length=255), nullable=True),
        if_not_exists=True,
    )
    op.add_column(
        "upload_requests",
        sa.Column("access_token", sa.Text(), nullable=True),
        if_not_exists=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("upload_requests", "access_token")
    op.drop_column("upload_requests", "collection")
    # ### end Alembic commands ###
