"""remove sdc v2

Revision ID: ee36be0a76c7
Revises: 53640eac191d
Create Date: 2026-01-04 13:16:48.357126

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ee36be0a76c7"
down_revision: Union[str, Sequence[str], None] = "53640eac191d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("upload_requests", "sdc_v2")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "upload_requests",
        sa.Column(
            "sdc_v2",
            mysql.LONGTEXT(charset="utf8mb4", collation="utf8mb4_bin"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
