# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from .BatchesList import BatchesList
from .BatchesListData import BatchesListData
from .BatchItem import BatchItem
from .BatchStats import BatchStats
from .BatchUploadItem import BatchUploadItem
from .BatchUploadsList import BatchUploadsList
from .BatchUploadsListData import BatchUploadsListData
from .CollectionImages import CollectionImages
from .CollectionImagesData import CollectionImagesData
from .Creator import Creator
from .DataValueEntityId import DataValueEntityId
from .DataValueGlobeCoordinate import DataValueGlobeCoordinate
from .DataValueQuantity import DataValueQuantity
from .DataValueTime import DataValueTime
from .Dates import Dates
from .DuplicateError import DuplicateError
from .EntityIdDataValue import EntityIdDataValue
from .EntityIdValueSnak import EntityIdValueSnak
from .Error import Error
from .ErrorLink import ErrorLink
from .ExistingPage import ExistingPage
from .ExternalIdValueSnak import ExternalIdValueSnak
from .FetchBatches import FetchBatches
from .FetchBatchesData import FetchBatchesData
from .FetchBatchUploads import FetchBatchUploads
from .FetchImages import FetchImages
from .GenericError import GenericError
from .GeoLocation import GeoLocation
from .GlobeCoordinateDataValue import GlobeCoordinateDataValue
from .GlobeCoordinateValueSnak import GlobeCoordinateValueSnak
from .Label import Label
from .MediaImage import MediaImage
from .NoValueSnak import NoValueSnak
from .QuantityDataValue import QuantityDataValue
from .QuantityValueSnak import QuantityValueSnak
from .Rank import Rank
from .Reference import Reference
from .RetryUploads import RetryUploads
from .SomeValueSnak import SomeValueSnak
from .Statement import Statement
from .StringDataValue import StringDataValue
from .StringValueSnak import StringValueSnak
from .SubscribeBatch import SubscribeBatch
from .SubscribeBatchesList import SubscribeBatchesList
from .SubscribeBatchesListData import SubscribeBatchesListData
from .Subscribed import Subscribed
from .TimeDataValue import TimeDataValue
from .TimeValueSnak import TimeValueSnak
from .TitleBlacklistedError import TitleBlacklistedError
from .UnsubscribeBatch import UnsubscribeBatch
from .UnsubscribeBatchesList import UnsubscribeBatchesList
from .Upload import Upload
from .UploadCreated import UploadCreated
from .UploadCreatedItem import UploadCreatedItem
from .UploadData import UploadData
from .UploadItem import UploadItem
from .UploadsComplete import UploadsComplete
from .UploadsUpdate import UploadsUpdate
from .UploadUpdateItem import UploadUpdateItem
from .UrlDataValue import UrlDataValue
from .UrlValueSnak import UrlValueSnak
from .WikibaseEntityType import WikibaseEntityType

__all__ = [
    "FetchBatches",
    "FetchBatchesData",
    "FetchBatchUploads",
    "FetchImages",
    "RetryUploads",
    "SubscribeBatch",
    "SubscribeBatchesList",
    "SubscribeBatchesListData",
    "UnsubscribeBatch",
    "UnsubscribeBatchesList",
    "Upload",
    "UploadData",
    "UploadItem",
    "Label",
    "Statement",
    "NoValueSnak",
    "SomeValueSnak",
    "EntityIdValueSnak",
    "EntityIdDataValue",
    "DataValueEntityId",
    "WikibaseEntityType",
    "ExternalIdValueSnak",
    "StringDataValue",
    "GlobeCoordinateValueSnak",
    "GlobeCoordinateDataValue",
    "DataValueGlobeCoordinate",
    "QuantityValueSnak",
    "QuantityDataValue",
    "DataValueQuantity",
    "StringValueSnak",
    "TimeValueSnak",
    "TimeDataValue",
    "DataValueTime",
    "UrlValueSnak",
    "UrlDataValue",
    "Rank",
    "Reference",
    "BatchesList",
    "BatchesListData",
    "BatchItem",
    "BatchStats",
    "BatchUploadsList",
    "BatchUploadsListData",
    "BatchUploadItem",
    "DuplicateError",
    "ErrorLink",
    "GenericError",
    "TitleBlacklistedError",
    "CollectionImages",
    "CollectionImagesData",
    "MediaImage",
    "Creator",
    "Dates",
    "ExistingPage",
    "GeoLocation",
    "Error",
    "Subscribed",
    "UploadCreated",
    "UploadCreatedItem",
    "UploadsComplete",
    "UploadsUpdate",
    "UploadUpdateItem",
]

# Rebuild models to resolve forward references
from pydantic import BaseModel

for name, cls in list(globals().items()):
    if isinstance(cls, type) and issubclass(cls, BaseModel) and cls is not BaseModel:
        try:
            cls.model_rebuild()
        except Exception:
            pass
