# Generated by @asyncapi/modelina
# Do not edit manually

# Rebuild models to resolve forward references
from pydantic import BaseModel

from .BatchesListData import BatchesListData
from .BatchesListPayload import BatchesListPayload
from .BatchItem import BatchItem
from .BatchStats import BatchStats
from .BatchUploadItem import BatchUploadItem
from .BatchUploadsListPayload import BatchUploadsListPayload
from .CollectionImagesData import CollectionImagesData
from .CollectionImagesPayload import CollectionImagesPayload
from .Creator import Creator
from .Dates import Dates
from .DuplicateError import DuplicateError
from .ErrorLink import ErrorLink
from .ErrorPayload import ErrorPayload
from .ExistingPage import ExistingPage
from .FetchBatchesData import FetchBatchesData
from .FetchBatchesPayload import FetchBatchesPayload
from .FetchBatchUploadsData import FetchBatchUploadsData
from .FetchBatchUploadsPayload import FetchBatchUploadsPayload
from .FetchImagesPayload import FetchImagesPayload
from .GenericError import GenericError
from .GeoLocation import GeoLocation
from .MediaImage import MediaImage
from .RetryUploadsData import RetryUploadsData
from .RetryUploadsPayload import RetryUploadsPayload
from .SubscribeBatchesListData import SubscribeBatchesListData
from .SubscribeBatchesListPayload import SubscribeBatchesListPayload
from .SubscribeBatchPayload import SubscribeBatchPayload
from .SubscribedPayload import SubscribedPayload
from .UnsubscribeBatchesListPayload import UnsubscribeBatchesListPayload
from .UnsubscribeBatchPayload import UnsubscribeBatchPayload
from .UploadCreatedItem import UploadCreatedItem
from .UploadCreatedPayload import UploadCreatedPayload
from .UploadData import UploadData
from .UploadItem import UploadItem
from .UploadPayload import UploadPayload
from .UploadsCompletePayload import UploadsCompletePayload
from .UploadsUpdatePayload import UploadsUpdatePayload
from .UploadUpdateItem import UploadUpdateItem

for name, cls in list(globals().items()):
    if isinstance(cls, type) and issubclass(cls, BaseModel) and cls is not BaseModel:
        try:
            cls.model_rebuild()
        except Exception:
            pass
