# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Optional, Union

from pydantic import BaseModel, ConfigDict, Field

from .DuplicatedSdcNotUpdatedError import DuplicatedSdcNotUpdatedError
from .DuplicatedSdcUpdatedError import DuplicatedSdcUpdatedError
from .DuplicateError import DuplicateError
from .GenericError import GenericError
from .Label import Label
from .TitleBlacklistedError import TitleBlacklistedError


class BatchUploadItem(BaseModel):
    id: int = Field()
    status: str = Field()
    filename: str = Field()
    wikitext: str = Field()
    batchid: Optional[int] = Field(default=None)
    userid: Optional[str] = Field(default=None)
    key: Optional[str] = Field(default=None)
    handler: Optional[str] = Field(default=None)
    labels: Optional[Label] = Field(default=None)
    result: Optional[str] = Field(default=None)
    error: Optional[
        Union[
            DuplicateError,
            DuplicatedSdcNotUpdatedError,
            DuplicatedSdcUpdatedError,
            GenericError,
            TitleBlacklistedError,
        ]
    ] = Field(default=None)
    success: Optional[str] = Field(default=None)
    last_edited_by: Optional[str] = Field(default=None)
    created_at: Optional[str] = Field(default=None)
    updated_at: Optional[str] = Field(default=None)
    image_id: Optional[str] = Field(default=None)

    model_config = ConfigDict(populate_by_name=True)
