# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field

from .BatchItem import BatchItem


class BatchesListData(BaseModel):
    items: List[BatchItem] = Field()
    total: int = Field()
