# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

from .BatchesListData import BatchesListData


class BatchesList(BaseModel):
    data: BatchesListData = Field()
    type: Literal["BATCHES_LIST"] = Field(default="BATCHES_LIST", frozen=True)
