# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from .BatchUploadsListData import BatchUploadsListData


class BatchUploadsList(BaseModel):
    data: BatchUploadsListData = Field()
    type: Literal["BATCH_UPLOADS_LIST"] = Field(
        default="BATCH_UPLOADS_LIST", frozen=True
    )
    nonce: str = Field(description="""Timestamp nonce to ensure change detection""")

    model_config = ConfigDict(populate_by_name=True)
