# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import List, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, field_validator

from .DuplicateError import DuplicateError
from .GenericError import GenericError
from .Label import Label
from .SdcV2 import SdcV2
from .Statement import Statement
from .TitleBlacklistedError import TitleBlacklistedError


class BatchUploadItem(BaseModel):
    id: int = Field()
    status: str = Field()
    filename: str = Field()
    wikitext: str = Field()
    batchid: Optional[int] = Field(default=None)
    userid: Optional[str] = Field(default=None)
    key: Optional[str] = Field(default=None)
    handler: Optional[str] = Field(default=None)
    sdc: List[Statement] = Field(default=[])
    sdc_v2: Optional[SdcV2] = Field(default=None)
    labels: Optional[Label] = Field(default=None)
    result: Optional[str] = Field(default=None)
    error: Optional[Union[DuplicateError, GenericError, TitleBlacklistedError]] = Field(
        default=None
    )
    success: Optional[str] = Field(default=None)
    created_at: Optional[str] = Field(default=None)
    updated_at: Optional[str] = Field(default=None)
    image_id: Optional[str] = Field(default=None)

    model_config = ConfigDict(populate_by_name=True)

    @field_validator("sdc", mode="before")
    @classmethod
    def parse_empty_list(cls, v):
        if v is None:
            return []
        return v
