# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field

from .BatchStats import BatchStats


class BatchItem(BaseModel):
    id: int = Field()
    created_at: str = Field()
    updated_at: str = Field()
    edit_group_id: Optional[str] = Field(default=None)
    username: str = Field()
    userid: str = Field()
    stats: BatchStats = Field()

    model_config = ConfigDict(populate_by_name=True)
