# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class BatchCreated(BaseModel):
    type: Literal["BATCH_CREATED"] = Field(default="BATCH_CREATED", frozen=True)
    data: int = Field(description="""Created batch identifier""")
    nonce: str = Field(description="""Timestamp nonce to ensure change detection""")

    model_config = ConfigDict(populate_by_name=True)
