# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class BatchStats(BaseModel):
    completed: int = Field(default=0)
    duplicate: int = Field(default=0)
    failed: int = Field(default=0)
    in_progress: int = Field(default=0)
    queued: int = Field(default=0)
    total: int = Field(default=0)

    model_config = ConfigDict(populate_by_name=True)
