# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

from .BatchUploadsListData import BatchUploadsListData


class BatchUploadsList(BaseModel):
    data: BatchUploadsListData = Field()
    type: Literal["BATCH_UPLOADS_LIST"] = Field(
        default="BATCH_UPLOADS_LIST", frozen=True
    )
