# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field

from .BatchItem import BatchItem
from .BatchUploadItem import BatchUploadItem


class BatchUploadsListData(BaseModel):
    batch: BatchItem = Field()
    uploads: List[BatchUploadItem] = Field()
