# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from pydantic import BaseModel, Field

from .BatchStats import BatchStats


class BatchItem(BaseModel):
    id: int = Field()
    created_at: str = Field()
    username: str = Field()
    userid: str = Field()
    stats: BatchStats = Field()
