# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class CameraInfo(BaseModel):
    make: Optional[str] = Field(default=None)
    model: Optional[str] = Field(default=None)
    is_pano: bool = Field()

    model_config = ConfigDict(populate_by_name=True)
