# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class CancelBatch(BaseModel):
    data: int = Field(description="""Batch identifier to cancel""")
    type: Literal["CANCEL_BATCH"] = Field(default="CANCEL_BATCH", frozen=True)

    model_config = ConfigDict(populate_by_name=True)
