# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from .CategoryCreatedResponseData import CategoryCreatedResponseData


class CategoryCreatedResponse(BaseModel):
    type: Literal["CATEGORY_CREATED_RESPONSE"] = Field(
        default="CATEGORY_CREATED_RESPONSE", frozen=True
    )
    data: CategoryCreatedResponseData = Field()
    nonce: str = Field(description="""Timestamp nonce to ensure change detection""")

    model_config = ConfigDict(populate_by_name=True)
