# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from .CategoriesDeletedResponseData import CategoriesDeletedResponseData


class CategoriesDeletedResponse(BaseModel):
    type: Literal["CATEGORIES_DELETED_RESPONSE"] = Field(
        default="CATEGORIES_DELETED_RESPONSE", frozen=True
    )
    data: CategoriesDeletedResponseData = Field()
    nonce: str = Field(description="""Timestamp nonce to ensure change detection""")

    model_config = ConfigDict(populate_by_name=True)
