# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from .CheckCategoriesDeletedData import CheckCategoriesDeletedData


class CheckCategoriesDeleted(BaseModel):
    type: Literal["CHECK_CATEGORIES_DELETED"] = Field(
        default="CHECK_CATEGORIES_DELETED", frozen=True
    )
    data: CheckCategoriesDeletedData = Field()

    model_config = ConfigDict(populate_by_name=True)
