# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import List, Literal

from pydantic import BaseModel, ConfigDict, Field


class CollectionImageIds(BaseModel):
    type: Literal["COLLECTION_IMAGE_IDS"] = Field(
        default="COLLECTION_IMAGE_IDS", frozen=True
    )
    data: List[str] = Field()
    nonce: str = Field(description="""Timestamp nonce to ensure change detection""")

    model_config = ConfigDict(populate_by_name=True)
