# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from pydantic import BaseModel, Field

from .Creator import Creator
from .MediaImage import MediaImage


class CollectionImagesData(BaseModel):
    images: dict[str, MediaImage] = Field()
    creator: Creator = Field()
