# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from .CollectionImagesData import CollectionImagesData


class CollectionImages(BaseModel):
    type: Literal["COLLECTION_IMAGES"] = Field(default="COLLECTION_IMAGES", frozen=True)
    data: CollectionImagesData = Field()
    nonce: str = Field(description="""Timestamp nonce to ensure change detection""")

    model_config = ConfigDict(populate_by_name=True)
