# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from .CreateCategoryData import CreateCategoryData


class CreateCategory(BaseModel):
    type: Literal["CREATE_CATEGORY"] = Field(default="CREATE_CATEGORY", frozen=True)
    data: CreateCategoryData = Field()

    model_config = ConfigDict(populate_by_name=True)
