# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class CreateBatch(BaseModel):
    type: Literal["CREATE_BATCH"] = Field(default="CREATE_BATCH", frozen=True)

    model_config = ConfigDict(populate_by_name=True)
