# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from pydantic import BaseModel, Field


class Creator(BaseModel):
    id: str = Field()
    username: str = Field()
    profile_url: str = Field()
