# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class CreateCategoryData(BaseModel):
    title: str = Field()
    text: str = Field()
    wikidata_qid: Optional[str] = Field(default=None)

    model_config = ConfigDict(populate_by_name=True)
