# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from enum import Enum


class DataValueType(Enum):
    EXTERNAL_MINUS_ID = "external-id"
    GLOBECOORDINATE = "globecoordinate"
    QUANTITY = "quantity"
    STRING = "string"
    TIME = "time"
    WIKIBASE_MINUS_ENTITYID = "wikibase-entityid"
