# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from .DeletePresetData import DeletePresetData


class DeletePreset(BaseModel):
    type: Literal["DELETE_PRESET"] = Field(default="DELETE_PRESET", frozen=True)
    data: DeletePresetData = Field()

    model_config = ConfigDict(populate_by_name=True)
