# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import List, Literal

from pydantic import BaseModel, ConfigDict, Field

from .ErrorLink import ErrorLink


class DuplicateError(BaseModel):
    links: List[ErrorLink] = Field()
    message: str = Field()
    type: Literal["duplicate"] = Field(default="duplicate", frozen=True)

    model_config = ConfigDict(populate_by_name=True)
