# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class Error(BaseModel):
    data: str = Field(description="""Error data""")
    type: Literal["ERROR"] = Field(default="ERROR", frozen=True)
