# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class ErrorLink(BaseModel):
    title: str = Field()
    url: str = Field()

    model_config = ConfigDict(populate_by_name=True)
