# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class FetchBatchUploads(BaseModel):
    data: int = Field(description="""Batch identifier""")
    type: Literal["FETCH_BATCH_UPLOADS"] = Field(
        default="FETCH_BATCH_UPLOADS", frozen=True
    )

    model_config = ConfigDict(populate_by_name=True)
