# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class FetchWantedCategoriesData(BaseModel):
    offset: int = Field(default=0)
    filter: Optional[str] = Field(default=None)

    model_config = ConfigDict(populate_by_name=True)
