# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class FetchBatchesData(BaseModel):
    page: int = Field(default=1)
    limit: int = Field(default=100)
    userid: Optional[str] = Field(
        description="""Optional user id to filter batches""", default=None
    )
    filter: Optional[str] = Field(
        description="""Optional filter text for batches (id or username)""",
        default=None,
    )

    model_config = ConfigDict(populate_by_name=True)
