# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from .FetchPresetsData import FetchPresetsData


class FetchPresets(BaseModel):
    type: Literal["FETCH_PRESETS"] = Field(default="FETCH_PRESETS", frozen=True)
    data: FetchPresetsData = Field()

    model_config = ConfigDict(populate_by_name=True)
