# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class FetchRedlinks(BaseModel):
    type: Literal["FETCH_REDLINKS"] = Field(default="FETCH_REDLINKS", frozen=True)

    model_config = ConfigDict(populate_by_name=True)
