# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from .ImageHandler import ImageHandler


class FetchPresetsData(BaseModel):
    handler: ImageHandler = Field()

    model_config = ConfigDict(populate_by_name=True)
