# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class FetchWantedCategories(BaseModel):
    type: Literal["FETCH_WANTED_CATEGORIES"] = Field(
        default="FETCH_WANTED_CATEGORIES", frozen=True
    )

    model_config = ConfigDict(populate_by_name=True)
