# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

from .FetchBatchesData import FetchBatchesData


class FetchBatches(BaseModel):
    data: FetchBatchesData = Field()
    type: Literal["FETCH_BATCHES"] = Field(default="FETCH_BATCHES", frozen=True)
