# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class GenericError(BaseModel):
    message: str = Field()
    type: Literal["error"] = Field(default="error", frozen=True)
