# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class GeoLocation(BaseModel):
    accuracy: Optional[int] = Field(default=None)
    compass_angle: float = Field()
    latitude: float = Field()
    longitude: float = Field()

    model_config = ConfigDict(populate_by_name=True)
