# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Any, Literal

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    field_validator,
    model_serializer,
    model_validator,
)

from .GlobeCoordinateDataValue import GlobeCoordinateDataValue


class GlobeCoordinateValueSnak(BaseModel):
    snaktype: Literal["value"] = Field(default="value", frozen=True)
    property: str = Field(description="""Property ID""")
    datatype: Literal["globe-coordinate"] = Field(
        default="globe-coordinate", frozen=True
    )
    datavalue: GlobeCoordinateDataValue = Field(
        description="""Globe coordinate data value"""
    )
    additional_properties: dict[str, Any] = Field(default={}, exclude=True)

    model_config = ConfigDict(populate_by_name=True)

    @field_validator("additional_properties", mode="before")
    @classmethod
    def parse_empty_dict(cls, v):
        if v is None:
            return {}
        return v

    @model_serializer(mode="wrap")
    def custom_serializer(self, handler):
        serialized_self = handler(self)
        additional_properties = getattr(self, "additional_properties")
        if additional_properties is not None:
            for key, value in additional_properties.items():
                # Never overwrite existing values, to avoid clashes
                if key not in serialized_self:
                    serialized_self[key] = value

        return serialized_self

    @model_validator(mode="before")
    @classmethod
    def unwrap_additional_properties(cls, data):
        if not isinstance(data, dict):
            try:
                data = data.model_dump()

            except AttributeError:
                return data

        data = data.copy()
        json_properties = list(data.keys())
        known_object_properties = [
            "snaktype",
            "property",
            "datatype",
            "datavalue",
            "additional_properties",
        ]
        unknown_object_properties = [
            element
            for element in json_properties
            if element not in known_object_properties
        ]
        # Ignore attempts that validate regular models, only when unknown input is used we add unwrap extensions
        if len(unknown_object_properties) == 0:
            return data

        known_json_properties = [
            "snaktype",
            "property",
            "datatype",
            "datavalue",
            "additionalProperties",
        ]
        additional_properties = data.get("additional_properties", {})
        for obj_key in unknown_object_properties:
            if not known_json_properties.__contains__(obj_key):
                additional_properties[obj_key] = data.pop(obj_key, None)
        data["additional_properties"] = additional_properties
        return data
