# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class ImageUrls(BaseModel):
    url: str = Field()
    original: str = Field()
    preview: str = Field()
    thumbnail: str = Field()

    model_config = ConfigDict(populate_by_name=True)
