# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from pydantic import BaseModel, Field


class Label(BaseModel):
    language: str = Field()
    value: str = Field()
