# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field, field_validator

from .CameraInfo import CameraInfo
from .Creator import Creator
from .Dates import Dates
from .ExistingPage import ExistingPage
from .GeoLocation import GeoLocation
from .ImageDimensions import ImageDimensions
from .ImageUrls import ImageUrls


class MediaImage(BaseModel):
    camera: CameraInfo = Field()
    creator: Creator = Field()
    dates: Dates = Field()
    description: Optional[str] = Field(default=None)
    dimensions: ImageDimensions = Field()
    existing: List[ExistingPage] = Field()
    id: str = Field()
    license: Optional[str] = Field(default=None)
    location: GeoLocation = Field()
    tags: List[str] = Field(default=[])
    title: str = Field()
    urls: ImageUrls = Field()

    model_config = ConfigDict(populate_by_name=True)

    @field_validator("tags", mode="before")
    @classmethod
    def parse_empty_list(cls, v):
        if v is None:
            return []
        return v
