# Generated by @asyncapi/modelina
# Do not edit manually

from __future__ import annotations

from typing import Any, List, Optional

from pydantic import BaseModel, Field, model_serializer, model_validator

from .Creator import Creator
from .Dates import Dates
from .ExistingPage import ExistingPage
from .GeoLocation import GeoLocation


class MediaImage(BaseModel):
    camera_make: Optional[str] = Field(default=None)
    camera_model: Optional[str] = Field(default=None)
    creator: Creator = Field()
    dates: Dates = Field()
    description: Optional[str] = Field(default=None)
    existing: List[ExistingPage] = Field()
    height: int = Field()
    id: str = Field()
    is_pano: Optional[bool] = Field(default=None)
    license: Optional[str] = Field(default=None)
    location: GeoLocation = Field()
    preview_url: str = Field()
    tags: Optional[List[str]] = Field(default=None)
    thumbnail_url: str = Field()
    title: str = Field()
    url: str = Field()
    url_original: str = Field()
    width: int = Field()
    additional_properties: Optional[dict[str, Any]] = Field(default=None, exclude=True)

    @model_serializer(mode="wrap")
    def custom_serializer(self, handler):
        serialized_self = handler(self)
        additional_properties = getattr(self, "additional_properties")
        if additional_properties is not None:
            for key, value in additional_properties.items():
                # Never overwrite existing values, to avoid clashes
                if key not in serialized_self:
                    serialized_self[key] = value

        return serialized_self

    @model_validator(mode="before")
    @classmethod
    def unwrap_additional_properties(cls, data):
        if not isinstance(data, dict):
            try:
                data = data.model_dump()
            except AttributeError:
                return data
        json_properties = list(data.keys())
        known_object_properties = [
            "camera_make",
            "camera_model",
            "creator",
            "dates",
            "description",
            "existing",
            "height",
            "id",
            "is_pano",
            "license",
            "location",
            "preview_url",
            "tags",
            "thumbnail_url",
            "title",
            "url",
            "url_original",
            "width",
            "additional_properties",
        ]
        unknown_object_properties = [
            element
            for element in json_properties
            if element not in known_object_properties
        ]
        # Ignore attempts that validate regular models, only when unknown input is used we add unwrap extensions
        if len(unknown_object_properties) == 0:
            return data

        known_json_properties = [
            "camera_make",
            "camera_model",
            "creator",
            "dates",
            "description",
            "existing",
            "height",
            "id",
            "is_pano",
            "license",
            "location",
            "preview_url",
            "tags",
            "thumbnail_url",
            "title",
            "url",
            "url_original",
            "width",
            "additionalProperties",
        ]
        additional_properties = data.get("additional_properties", {})
        for obj_key in unknown_object_properties:
            if not known_json_properties.__contains__(obj_key):
                additional_properties[obj_key] = data.pop(obj_key, None)
        data["additional_properties"] = additional_properties
        return data
