# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field

from .Creator import Creator
from .Dates import Dates
from .ExistingPage import ExistingPage
from .GeoLocation import GeoLocation


class MediaImage(BaseModel):
    camera_make: Optional[str] = Field(default=None)
    camera_model: Optional[str] = Field(default=None)
    creator: Creator = Field()
    dates: Dates = Field()
    description: Optional[str] = Field(default=None)
    existing: List[ExistingPage] = Field()
    height: int = Field()
    id: str = Field()
    is_pano: Optional[bool] = Field(default=None)
    license: Optional[str] = Field(default=None)
    location: GeoLocation = Field()
    preview_url: str = Field()
    tags: Optional[List[str]] = Field(default=None)
    thumbnail_url: str = Field()
    title: str = Field()
    url: str = Field()
    url_original: str = Field()
    width: int = Field()
