# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict, Field

from .MediaImage import MediaImage


class PartialCollectionImagesData(BaseModel):
    images: List[MediaImage] = Field()
    collection: str = Field()

    model_config = ConfigDict(populate_by_name=True)
