# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from .PartialCollectionImagesData import PartialCollectionImagesData


class PartialCollectionImages(BaseModel):
    type: Literal["PARTIAL_COLLECTION_IMAGES"] = Field(
        default="PARTIAL_COLLECTION_IMAGES", frozen=True
    )
    data: PartialCollectionImagesData = Field()
    nonce: str = Field(description="""Timestamp nonce to ensure change detection""")

    model_config = ConfigDict(populate_by_name=True)
