# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict, Field

from .PresetItem import PresetItem


class PresetsListData(BaseModel):
    handler: str = Field()
    presets: List[PresetItem] = Field()

    model_config = ConfigDict(populate_by_name=True)
