# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from .PresetsListData import PresetsListData


class PresetsList(BaseModel):
    type: Literal["PRESETS_LIST"] = Field(default="PRESETS_LIST", frozen=True)
    data: PresetsListData = Field()
    nonce: str = Field(description="""Timestamp nonce to ensure change detection""")

    model_config = ConfigDict(populate_by_name=True)
