# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from .RecategorizeFilesResponseData import RecategorizeFilesResponseData


class RecategorizeFilesResponse(BaseModel):
    type: Literal["RECATEGORIZE_FILES_RESPONSE"] = Field(
        default="RECATEGORIZE_FILES_RESPONSE", frozen=True
    )
    data: RecategorizeFilesResponseData = Field()
    nonce: str = Field(description="""Timestamp nonce to ensure change detection""")

    model_config = ConfigDict(populate_by_name=True)
