# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class RecategorizeFilesResponseData(BaseModel):
    source: str = Field()
    count: int = Field()

    model_config = ConfigDict(populate_by_name=True)
