# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from .RecategorizeFilesData import RecategorizeFilesData


class RecategorizeFiles(BaseModel):
    type: Literal["RECATEGORIZE_FILES"] = Field(
        default="RECATEGORIZE_FILES", frozen=True
    )
    data: RecategorizeFilesData = Field()

    model_config = ConfigDict(populate_by_name=True)
