# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from .RedlinksResponseData import RedlinksResponseData


class RedlinksResponse(BaseModel):
    type: Literal["REDLINKS_RESPONSE"] = Field(default="REDLINKS_RESPONSE", frozen=True)
    data: RedlinksResponseData = Field()
    nonce: str = Field(description="""Timestamp nonce to ensure change detection""")

    model_config = ConfigDict(populate_by_name=True)
