# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class RetryUploads(BaseModel):
    data: int = Field(description="""Batch identifier""")
    type: Literal["RETRY_UPLOADS"] = Field(default="RETRY_UPLOADS", frozen=True)
