# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from .SavePresetData import SavePresetData


class SavePreset(BaseModel):
    type: Literal["SAVE_PRESET"] = Field(default="SAVE_PRESET", frozen=True)
    data: SavePresetData = Field()

    model_config = ConfigDict(populate_by_name=True)
