# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field

from .Label import Label


class SavePresetData(BaseModel):
    preset_id: Optional[int] = Field(default=None)
    title: str = Field()
    title_template: str = Field()
    labels: Optional[Label] = Field(default=None)
    categories: Optional[str] = Field(default=None)
    exclude_from_date_category: bool = Field(default=False)
    is_default: bool = Field(default=False)
    handler: str = Field()

    model_config = ConfigDict(populate_by_name=True)
