# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from .GeoLocation import GeoLocation


class SdcV2(BaseModel):
    type: Literal["mapillary"] = Field(default="mapillary", frozen=True)
    version: Literal[1] = Field(default=1, frozen=True)
    creator_username: str = Field()
    mapillary_image_id: str = Field()
    taken_at: str = Field()
    source_url: str = Field()
    location: GeoLocation = Field()
    width: int = Field()
    height: int = Field()
    include_default_copyright: bool = Field()

    model_config = ConfigDict(populate_by_name=True)
