# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from enum import Enum


class SnakDataType(Enum):
    EXTERNAL_MINUS_ID = "external-id"
    GLOBE_MINUS_COORDINATE = "globe-coordinate"
    QUANTITY = "quantity"
    STRING = "string"
    TIME = "time"
    URL = "url"
    WIKIBASE_MINUS_ITEM = "wikibase-item"
