# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class SubscribeBatch(BaseModel):
    data: int = Field(description="""Batch identifier""")
    type: Literal["SUBSCRIBE_BATCH"] = Field(default="SUBSCRIBE_BATCH", frozen=True)
