# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

from .SubscribeBatchesListData import SubscribeBatchesListData


class SubscribeBatchesList(BaseModel):
    data: SubscribeBatchesListData = Field()
    type: Literal["SUBSCRIBE_BATCHES_LIST"] = Field(
        default="SUBSCRIBE_BATCHES_LIST", frozen=True
    )
