# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class SubscribeBatchesListData(BaseModel):
    filter: Optional[str] = Field(
        description="""Filter text for batches""", default=None
    )
    userid: Optional[str] = Field(
        description="""User id to filter batches""", default=None
    )

    model_config = ConfigDict(populate_by_name=True)
