# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class Subscribed(BaseModel):
    data: int = Field(description="""Subscribed batch identifier""")
    type: Literal["SUBSCRIBED"] = Field(default="SUBSCRIBED", frozen=True)
