# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class TitleBlacklistedError(BaseModel):
    message: str = Field()
    type: Literal["title_blacklisted"] = Field(default="title_blacklisted", frozen=True)

    model_config = ConfigDict(populate_by_name=True)
