# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class TryBatchRetrieval(BaseModel):
    type: Literal["TRY_BATCH_RETRIEVAL"] = Field(
        default="TRY_BATCH_RETRIEVAL", frozen=True
    )
    data: str = Field()
    nonce: str = Field(description="""Timestamp nonce to ensure change detection""")

    model_config = ConfigDict(populate_by_name=True)
