# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class UnsubscribeBatch(BaseModel):
    type: Literal["UNSUBSCRIBE_BATCH"] = Field(default="UNSUBSCRIBE_BATCH", frozen=True)
