# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class UnsubscribeBatchesList(BaseModel):
    type: Literal["UNSUBSCRIBE_BATCHES_LIST"] = Field(
        default="UNSUBSCRIBE_BATCHES_LIST", frozen=True
    )

    model_config = ConfigDict(populate_by_name=True)
