# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field

from .UploadItem import UploadItem


class UploadData(BaseModel):
    items: List[UploadItem] = Field()
    handler: Optional[str] = Field(default=None)

    model_config = ConfigDict(populate_by_name=True)
