# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import List, Literal

from pydantic import BaseModel, ConfigDict, Field

from .UploadUpdateItem import UploadUpdateItem


class UploadsUpdate(BaseModel):
    type: Literal["UPLOADS_UPDATE"] = Field(default="UPLOADS_UPDATE", frozen=True)
    data: List[UploadUpdateItem] = Field()
    nonce: str = Field(description="""Timestamp nonce to ensure change detection""")

    model_config = ConfigDict(populate_by_name=True)
