# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Optional, Union

from pydantic import BaseModel, ConfigDict, Field

from .DuplicateError import DuplicateError
from .GenericError import GenericError
from .TitleBlacklistedError import TitleBlacklistedError


class UploadUpdateItem(BaseModel):
    id: int = Field()
    batchid: int = Field()
    status: str = Field()
    key: str = Field()
    error: Optional[Union[DuplicateError, GenericError, TitleBlacklistedError]] = Field(
        default=None
    )
    success: Optional[str] = Field(default=None)
    handler: str = Field()

    model_config = ConfigDict(populate_by_name=True)
