# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class UploadSliceAck(BaseModel):
    type: Literal["UPLOAD_SLICE_ACK"] = Field(default="UPLOAD_SLICE_ACK", frozen=True)
    data: int = Field(description="""Acknowledged slice identifier""")
    nonce: str = Field(description="""Timestamp nonce to ensure change detection""")

    model_config = ConfigDict(populate_by_name=True)
