# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Optional, Union

from pydantic import BaseModel, Field

from .DuplicateError import DuplicateError
from .GenericError import GenericError


class UploadUpdateItem(BaseModel):
    id: int = Field()
    batchid: int = Field()
    status: str = Field()
    key: str = Field()
    error: Optional[Union[DuplicateError, GenericError]] = Field(default=None)
    success: Optional[str] = Field(default=None)
    handler: str = Field()
