# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import List, Literal

from pydantic import BaseModel, Field

from .UploadCreatedItem import UploadCreatedItem


class UploadCreated(BaseModel):
    type: Literal["UPLOAD_CREATED"] = Field(default="UPLOAD_CREATED", frozen=True)
    data: List[UploadCreatedItem] = Field()
