# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict, Field

from .UploadItem import UploadItem


class UploadSliceData(BaseModel):
    batchid: int = Field()
    sliceid: int = Field()
    items: List[UploadItem] = Field()
    handler: str = Field(default="mapillary")

    model_config = ConfigDict(populate_by_name=True)
