# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field, field_validator

from .Label import Label
from .Statement import Statement


class UploadItem(BaseModel):
    id: str = Field()
    input: str = Field()
    title: str = Field()
    wikitext: str = Field()
    labels: Optional[Label] = Field(default=None)
    sdc: List[Statement] = Field(default=[])

    model_config = ConfigDict(populate_by_name=True)

    @field_validator("sdc", mode="before")
    @classmethod
    def parse_empty_list(cls, v):
        if v is None:
            return []
        return v
