# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class UploadsComplete(BaseModel):
    data: int = Field(description="""Completed batch identifier""")
    type: Literal["UPLOADS_COMPLETE"] = Field(default="UPLOADS_COMPLETE", frozen=True)
