# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field

from .Label import Label


class UploadItem(BaseModel):
    id: str = Field()
    input: str = Field()
    title: str = Field()
    wikitext: str = Field()
    labels: Optional[Label] = Field(default=None)
    copyright_override: Optional[bool] = Field(default=False)

    model_config = ConfigDict(populate_by_name=True)
