# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class UploadCreatedItem(BaseModel):
    id: int = Field()
    status: str = Field()
    image_id: str = Field()
    input: str = Field()
    batchid: int = Field()

    model_config = ConfigDict(populate_by_name=True)
