# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class UploadsComplete(BaseModel):
    data: int = Field(description="""Completed batch identifier""")
    type: Literal["UPLOADS_COMPLETE"] = Field(default="UPLOADS_COMPLETE", frozen=True)
    nonce: str = Field(description="""Timestamp nonce to ensure change detection""")

    model_config = ConfigDict(populate_by_name=True)
