# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import Any, List, Optional

from pydantic import BaseModel, Field

from .Label import Label


class UploadItem(BaseModel):
    id: str = Field()
    input: str = Field()
    title: str = Field()
    wikitext: str = Field()
    labels: Optional[Label] = Field(default=None)
    sdc: Optional[List[Any]] = Field(default=None)
