# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class WantedCategoryItem(BaseModel):
    title: str = Field()
    subcats: int = Field()
    files: int = Field()
    pages: int = Field()
    total: int = Field()

    model_config = ConfigDict(populate_by_name=True)
