# Auto-generated by @asyncapi/modelina
# DO NOT EDIT MANUALLY

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict, Field

from .WantedCategoryItem import WantedCategoryItem


class WantedCategoriesResponseData(BaseModel):
    items: List[WantedCategoryItem] = Field()

    model_config = ConfigDict(populate_by_name=True)
